name: HyperMerchant
main: grokswell.hypermerchant.HyperMerchantPlugin
version: 1.29
description: Inventory menu to be used with HyperConomy shops and NPC trait for Citizens2.
author: Grokswell
authors: [Grokswell] 
database: false
depend: [HyperConomy]
softdepend: [Citizens]
commands:
   shopmenu:
      description: Must be standing in shop to use. Browse a HyperConomy shop's inventory. Buy and Sell with ease.
      usage: /shopmenu
      permission: hypermerchant.menu
      permission-message: You do not have permission to use command /shopmenu.
      aliases: [smenu,storemenu]
   remotemenu:
      description: Browse a HyperConomy shop's inventory. Buy and sell with ease.
      usage: /remotemenu [shopname]
      permission: hypermerchant.remote
      permission-message: You do not have permission to use command /remotemenu.
      aliases: [rmenu]
   remoteshoplist:
      description: List shop names in a format that can be used with /remotemenu.
      usage: /remoteshoplist
      permission: hypermerchant.remote
      permission-message: You do not have permission to use command /remoteshoplist.
      aliases: [rslist]
   hmerchant:
      description: Set the properties of the currently selected hypermerchant npc.
      usage: "\n§4/hmerchant §csetshop §a[shopname] §6[--id idnum] §e- Set shop of selected hypermerchant.
  	    Set to shop player is standing in if no [shopname] argument provided.\n\n
  	    §4/hmerchant §coffduty §6[--id idnum] §e- Toggle npc in and out of offduty mode.\n\n
        §4/hmerchant §cgreeting §a[welcome message] §6[--id idnum] §e- Set text NPC says upon player interaction.
  	    Leave [welcome message] argument empty for no text.\n\n
        §4/hmerchant §cfarewell §a[goodbye message] §6[--id idnum] §e- Set text NPC says upon player closing menu.
  	    Leave [goodbye message] argument empty for no text.\n\n
        §4/hmerchant §cdenial §a[deny message] §6[--id idnum] §e- Set text NPC says when player is not permitted to use a shop.
  	    Leave [deny message] argument empty for no text.\n\n
  	    §4/hmerchant §cclosed §a[closed message] §6[--id idnum] §e- Set text NPC says to a player when NPC is off duty.
  	    Leave [closed message] argument empty for no text.\n\n
  	    §4/hmerchant §clist §e- List information of all existing hypermerchant NPCs.\n\n
  	    §4/hmerchant §cinfo §6[--id idnum] §e- Show information of a single hypermerchant."
      permission: hypermerchant.manage
      permission-message: You do not have permission to use command /hmerchant.
      aliases: [hmerch]
    
permissions:
   hypermerchant.*:
      description: Gives access to all HyperMerchant commands
      children:
         hypermerchant.menu: true
         hypermerchant.remote: true
         hypermerchant.npc: true
         hypermerchant.manage: true
   hypermerchant.menu:
      description: Allow use of the /shopmenu command.
      default: true
   hypermerchant.npc:
      description: Allow interaction with hypermerchant npc.
      default: true
   hypermerchant.remote:
      description: Allow use of the /remotemenu command.
      default: op
   hypermerchant.manage:
      description: Allow use of the /hmerchant command.
      default: op
   creative.hypermerchant:
      description: Allow player to purchase and sell while in creative mode.
      default: false